# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

# Set a known clone folder
clone_folder: c:\projects\nodegit

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "John Doe"
  - git config --global user.email johndoe@example.com

# what combinations to test
environment:
  GYP_MSVS_VERSION: 2013
  JOBS: 4
  BUILD_ONLY: true
  matrix:
    # Node.js
    # io.js
    - nodejs_version: "2"

matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: "2"

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET GIT_SSH=c:\projects\nodegit\vendor\plink.exe
  - ps: Start-Process c:\projects\nodegit\vendor\pageant.exe c:\projects\nodegit\vendor\private.ppk
  - cmd: npm install -g node-gyp
  - set
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm test

on_success:
  - IF %APPVEYOR_REPO_TAG%==true npm install -g node-pre-gyp
  - IF %APPVEYOR_REPO_TAG%==true npm install -g aws-sdk
  - IF %APPVEYOR_REPO_TAG%==true node-pre-gyp package
  - IF %APPVEYOR_REPO_TAG%==true node-pre-gyp publish

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off

branches:
  only:
    - master
    - v0.3
